spring.application.name=backend

# Server-port
server.port=8080

# Loggning
logging.level.org.springframework=INFO
logging.level.com.example.myproject=DEBUG



spring.datasource.url=jdbc:postgresql://localhost:5432/stockreports
spring.datasource.username=postgres
spring.datasource.password=Kalleanka123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
